# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0004_auto_20170307_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField(max_length=10)),
            ],
        ),
    ]
