# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('File_Comparison', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='first_description',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='first_document',
        ),
        migrations.AddField(
            model_name='document',
            name='second_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='second_document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/django/'),
            preserve_default=False,
        ),
    ]
