# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_auto_20170215_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='title1',
        ),
    ]
